# pod-secret-consumer.yaml
apiVersion: v1
kind: Pod
metadata:
  name: secret-consumer
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: secret-vol
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: secret-vol
      secret:
        secretName: my-secret

