#This firsr yaml file is for Role creation and second one is RoleBinding. 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: default
rules:
  - apiGroups: [""]         #core API group (Secrets, Pods, etc.)
    resources: ["secrets"]
    verbs: ["get"]          #allows read-only access (get = view a single Secret)

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-secret-reader
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default           
    namespace: default
roleRef:
  kind: Role
  name: secret-reader         #above role is binded now.
  apiGroup: rbac.authorization.k8s.io

