apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
spec:
  clusterIP: None   # Headless service for stable pod network IDs
  selector:
    app: mysql
  ports:
  - port: 3306
    name: mysql


#kubectl apply -f mysql-headless-service.yaml

